"""empty message

Revision ID: 0292061ed502
Revises: b83a4d56c28e
Create Date: 2020-07-04 15:20:38.546661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0292061ed502'
down_revision = 'b83a4d56c28e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'video', 'professional', ['author_id'], ['id'])
    op.drop_column('video', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('author', sa.VARCHAR(length=80), nullable=True))
    op.drop_constraint(None, 'video', type_='foreignkey')
    # ### end Alembic commands ###
