"""video table

Revision ID: b83a4d56c28e
Revises: afc1facabd42
Create Date: 2020-07-03 17:34:28.385629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83a4d56c28e'
down_revision = 'afc1facabd42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'video', 'professional', ['author_id'], ['id'])
    op.drop_column('video', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('author', sa.VARCHAR(length=80), nullable=True))
    op.drop_constraint(None, 'video', type_='foreignkey')
    op.drop_column('video', 'author_id')
    # ### end Alembic commands ###
